### ISSUE TITLE
Finish implementation of password recovery

### ISSUE THREAD

**Issue by kparkov** [bitkompagniet/mugs#48]
I don't know exactly hos much was implemented the first time around, but I think there is a store method and an endpoint - but I believe it is incomplete.

The way it should work is:

- [ ] Call `GET /recovery/:email` to ask for a recovery token.
- [ ] The token is set on the user, and the e-mail is sent. At this point we want it to point at a `passwordRecoveryUrl` set as an `ENV` var. We want to suffix the token as `${passwordRecoveryUrl}/${token}`.
- [ ] Another endpoint, `POST /recovery/:token`, will take a `{ email: 'email', password: 'newPass' }` body. If the token **OR** the e-mail does not match, it should return `404`.

**Comment by neheren** [comment]
I think it was fixed by:
https://github.com/bitkompagniet/mugs/commit/a58f4f7c1c35b41d3b923a88f1aa68930cf36453

**Comment by neheren** [comment]
and https://github.com/bitkompagniet/mugs/issues/66

**Comment by kparkov** [comment]
Clearly not fixed, as there are no password recovery methods anywhere.
